### ISSUE TITLE
项目无法运行 / project can't run

### ISSUE THREAD

**Issue by huyaocode** [kenberkeley/quiz#1]
你好，我对你的这个项目非常非常感兴趣！我也正想用 next.js 做一个东西，但是无法运行起来项目。我甚至愿意为你的项目付费！ 

求你指导我一下怎么把这个项目运行起来！

**Comment by kenberkeley** [comment]
在根目录运行 yarn install

打开两个命令行窗口，先后执行
* yarn run server:dev
* yarn run client:dev

**Comment by kenberkeley** [comment]
本项目旨在打造 TS Full Stack 最佳实践，目前仍在探索阶段。开源社区也有类似的项目，例如 https://nx.dev ，但它不能解决各种 libs / frameworks not playing well 的问题，而我的探索就是为了填补这个空缺。

**Comment by huyaocode** [comment]
yarn run client:dev 报错，详情如下：

`➜  quiz git:(master) yarn run client:dev
yarn run v1.16.0
$ env-cmd -e dev yarn workspace client run dev
$ npm run clean:dist
npm WARN lifecycle The node binary used for scripts is /var/folders/0j/b4bc1ph103z0pg_65hch3tzw0000gn/T/yarn--1582205428226-0.216016501963759/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> client@0.0.1 clean:dist /Users/bytedance/Documents/quiz/packages/client
> del .next

$ next dev -p $CLIENT_PORT
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3030 ...
> Using "webpackDevMiddleware" config function defined in next.config.js.
> Using external babel configuration
> Location: "/Users/bytedance/Documents/quiz/packages/client/.babelrc.js"
[ error ] /Users/bytedance/Documents/quiz/node_modules/@nodelib/fs.scandir/out/adapters/fs.js
Module not found: Can't resolve 'fs' in '/Users/bytedance/Documents/quiz/node_modules/@nodelib/fs.scandir/out/adapters'
[ wait ]  compiling ...
[ error ] /Users/bytedance/Documents/quiz/node_modules/@nodelib/fs.scandir/out/adapters/fs.js
Module not found: Can't resolve 'fs' in '/Users/bytedance/Documents/quiz/node_modules/@nodelib/fs.scandir/out/adapters'
`
